version: 2
jobs:
  build:
    docker:
      - image: node:11.10.1
    environment:
      CI: false

    steps:
      - checkout

      - run: yarn install
      # run: yarn run test
      - run: yarn run build

  deploy:    
    docker:
      - image: buildpack-deps:trusty
    steps:  
      - checkout
      - run: 
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-and-deploy: 
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master